# Generated by Django 3.0 on 2024-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
