# Generated by Django 3.0 on 2024-02-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0002_customers_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='age',
        ),
    ]
