# Generated by Django 3.0 on 2024-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0003_remove_customers_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_repayment',
            new_name='monthly_installment',
        ),
        migrations.AddField(
            model_name='customers',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='current_debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customers',
            name='monthly_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(default=100000, primary_key=True, serialize=False),
        ),
    ]
