# Generated by Django 3.0 on 2024-02-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0006_auto_20240208_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='current_debt',
        ),
    ]
