# Generated by Django 3.0 on 2024-02-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0007_auto_20240209_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
