# Generated by Django 3.0 on 2024-02-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0008_auto_20240209_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
